resilience4j:
  circuitbreaker:
    instances:
      productService:
        baseConfig: default
        slidingWindowSize: 10
        failureRateThreshold: 50
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - com.example.order_service.api.common.exception.server.InternalServerException
        ignoreExceptions:
          - com.example.order_service.api.common.exception.NotFoundException

order:
  topics:
    # 발행
    deduct-inventory: "order.saga.inventory.deduct"
    used-coupon: "order.saga.coupon.used"
    used-point: "order.saga.point.used"
    # 수신
    product-result: "product.saga.result"
    coupon-result: "coupon.saga.result"
    user-result: "user.saga.result"