spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

product:
  topics:
    ## 주문 상품 재고 감소 요청 토픽
    order-result: "order.saga.product.request"
    ## 주문 상품 재고 감소 성공 토픽
    order-request: "product.saga.result"