global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'buynest-services'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://host.docker.internal:8761/eureka'

    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
        action: lowercase
        
      - source_labels: [__meta_eureka_app_name]
        regex: 'GATEWAY-SERVICE|ORDER-SERVICE|PRODUCT-SERVICE|USER-SERVICE'
        action: keep

      - source_labels: [__address__]
        regex: '.*:(\d+)' 
        target_label: __address__
        replacement: 'host.docker.internal:$1'

  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8761']
        labels:
          application: 'DISCOVERY-SERVICE'