spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ecommerce-kubernetes/config.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          default-label: main
          search-paths: /
  kafka:
    bootstrap-servers: localhost:9092
logging:
  loki:
    url: http://localhost:3100/loki/api/v1/push