spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ecommerce-kubernetes/config.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          default-label: main
          search-paths: /
  kafka:
    bootstrap-servers: kafka:29092
logging:
  level:
    root: INFO
    org.springframework.web: WARN
  loki:
    url: http://loki:3100/loki/api/v1/push